### ISSUE TITLE
Consider removing Scipy dependecies

### ISSUE THREAD

**Issue by E3V3A** [ulikoehler/UliEngineering#2]
Your package is using Scipy as a dependence, mainly for constants and FFT. However, Scipy is a huge package and often cause a lot of installation difficulties. Please consider extracting what few things are needed from Scipy instead, or make it an optional dependency.

**Comment by ulikoehler** [comment]
Thanks for reporting this! Since I have scipy installed by default on pretty much all environments, I didn't consider this an issue so far.

The main motivation for me using scipy is `scipy.fftpack` which is approx twice the speed of numpy for large-ish real-only FFTs (which I do quite often). But I believe I can make them compatible and make scipy optional. About the constants, I'll figure out some other way of using them.

I'll keep you updated.

**Comment by ulikoehler** [comment]
I've removed as much dependencies as I could without creating horribly duplicated code. Scipy is now an optional dependency, but the following modules will still not work without it:

 * UliEngineering.Length
 * UliEngineering.SignalProcessing.Interpolation
 * UliEngineering.SignalProcessing.Correlation
 * UliEngineering.Physics.JohnsonNyquistNoise
 * Some functions in UliEngineering.SignalProcessing.Simulation
 * Some functions in UliEngineering.SignalProcessing.Selection

Some other modules fall back to alternate functions like numpy.fft if scipy is not installed.

**Comment by E3V3A** [comment]
Wow, that was fast!
Thanks @ulikoehler 

I wanted to use your package for finding resistor values, but was disappointed that I needed to install the entire Scipy to have it work. So I had to hack into it and had to create my own libs, but doing that, I would not be able to give you feedback on some bugs and fixes in the resistors library.
